package it.polimi.se2018.observable;

/**
 * @author davide yi xian hu
 */
public interface GameEventObservable extends ChooseDraftDieValueObservable, DecreaseDieValueObservable, DraftAndPlaceNoAdjacentObservable, DraftAndPlaceAgainObservable, DraftAndPlaceObservable, EndTurnObservable, FlipDraftDieObservable, IncreaseDieValueObservable, MoveDieIgnoreColorRestrictionObservable, MoveDieIgnoreValueRestrictionObservable, MoveDieMatchColorRoundTrackObservable, MoveDieRespectAllRestrictionsObservable, RerollDraftDieObservable, RerollAllDraftDiceObservable, SwapDraftDieWithDiceBagDieObservable, SwapDraftDieWithRoundTrackDieObservable, UseToolCardObservable, WindowPatternChosenObservable{

}
